import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../app/layout/Navbar.jsx"
import Footer from "./layout/Footer.jsx"
import WhatsAppFloat from "../Componants/WhatsappIcon/WhatsAppFloat.jsx"
import { TracingBeam } from "../ui/Tracing_Beam.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div><Navbar/></div>
        <TracingBeam>
          {children}
        </TracingBeam>
        <Footer/>
        <WhatsAppFloat/>
      </body>
    </html>
  );
}
